In [1]:
#import Numpy Library
import numpy as np

In [2]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [3]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [4]:
#arrays with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#arrays with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#array with empty
array_empty = np.empty((2,3))
array_empty

array([[1.73e-321, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [7]:
#array with arrange method
np_arange = np.arange(12)

In [8]:
#print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
#reshape method to chenge/create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#linspace for linearty(equal) spaced data elements
np_linspce = np.linspace(1,6,5)

In [11]:
#print linespaced array
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [12]:
#one dimensional array
oneD_array = np.arange(15)

In [13]:
#print 1Darray
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [15]:
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
# Tree dimentional array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [18]:
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(ThreeD_array)