In [1]:
#import require libraries and dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
#view feature names of the dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
#view target of the dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
#define features and target objects
x_feature = iris_dataset.data
y_target = iris_dataset.target

In [5]:
#create object with new values for prediction
x_new = [[3,5,4,1],[5,3,4,2]]

In [6]:
#use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()

In [8]:
#fit the data into the logistic regression estimator
logReg.fit(x_feature,y_target)

C:\Users\Aabha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
#predict the outcome using Logistic regression estimator
logReg.predict(x_new)

array([0, 1])

In [10]:
#import library for model persistence
import pickle as pkl

In [11]:
#use dumps method to persist the model
persist_model = pkl.dumps(logReg)
persist_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eKdX\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x08\x00\x00\x00classes_q\x15cnumpy.core.multiarray\n_reconstruct\nq\x16cnumpy\nndarray\nq\x17K\x00\x85q\x18C\x01bq\x19\x87q\x1aRq\x1b(K\x01K\x03\x85q\x1ccnumpy\ndtype\nq\x1dX\x02\x00\x00\x00i4q\x1eK\x00K\x01\x87q\x1fRq (K\x03X\x01\x00\x00\x00<q!NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq"b\x89C\x0c\x00\x00\x00

In [12]:
#use joblib.dump to persist the model to a file
from sklearn.externals import joblib
joblib.dump(logReg,'regresfilename.pkl')

C:\Users\Aabha\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['regresfilename.pkl']

In [13]:
#use joblib.load to persist the model to a file
#create new estimator from the saved model
new_logreg_estimator = joblib.load('regresfilename.pkl')

In [14]:
#view the new estimator
new_logreg_estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
#validate and use new estimator to predict
new_logreg_estimator.predict(x_new)

array([0, 1])